BaseProject/Controllers/AlumnosController.cs
using BaseProject.DB;
using BaseProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    [Authorize(Roles = "it_mantenimiento")]
    public class AlumnosController : Controller
    {
        // GET: Alumnos
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ObtenerTabla()
        {
            using(var db = new VotacionesEntities())
            {
                var data = db.Alumnos.Select(x => new AlumnosViewModel
                {
                    Id = x.Id,
                    Grado = x.Grado,
                    Identidad = x.Identidad,
                    Jornada = x.Jornada,
                    ModalidadId = x.ModalidadId,
                    Nombre = x.Nombre,
                    Seccion = x.Seccion
                }).ToList();

                return Json(new { data = data }, JsonRequestBehavior.AllowGet);

            }
        }

        [HttpGet]
        public ActionResult CrearAlumno()
        {
            return PartialView(new AlumnosViewModel());
        }

        [HttpPost]
        public ActionResult CrearAlumno(AlumnosViewModel model)
        {
            try
            {
                using (var db = new VotacionesEntities())
                {

                    var existe = db.Alumnos.FirstOrDefault(x => x.Identidad == model.Identidad);

                    if (existe != null)
                        return Json(new ResponseMessage { Ok = false, Message = $"El numero de identidad {model.Identidad} ya se encuentra registrado" });

                    var alumno = new Alumnos
                    {
                        Grado = model.Grado,
                        Identidad = model.Identidad,
                        Jornada = model.Jornada,
                        ModalidadId = model.ModalidadId,
                        Nombre = model.Nombre,
                        Seccion = model.Seccion
                    };

                    db.Alumnos.Add(alumno);
                    db.SaveChanges();

                    return Json(new ResponseMessage { Ok = true, Message = $"Alumno {model.Nombre} creado exitosamente!" });

                }
            }
            catch(Exception ex) { return Json(new ResponseMessage { Ok = false, Message = $"Error {ex.Message}" }); }
        }

        [HttpGet]
        public ActionResult EditarAlumno(int Id)
        {
            using(var db = new VotacionesEntities())
            {
                var alumno = db.Alumnos.Where(x => x.Id == Id).Select(x => new AlumnosViewModel
                {
                    Id = x.Id,
                    Grado = x.Grado,
                    Identidad = x.Identidad,
                    Jornada = x.Jornada,
                    ModalidadId = x.ModalidadId,
                    Nombre = x.Nombre,
                    Seccion = x.Seccion
                }).FirstOrDefault();

                return PartialView(alumno);
            }
        }

        [HttpPost]
        public ActionResult EditarAlumno(AlumnosViewModel model)
        {
            using(var db = new VotacionesEntities())
            {
                var alumno = db.Alumnos.FirstOrDefault(x => x.Id == model.Id);

                alumno.Identidad = model.Identidad;
                alumno.Nombre = model.Nombre;
                alumno.Seccion = model.Seccion;
                alumno.Jornada = model.Jornada;
                alumno.ModalidadId = model.ModalidadId;
                alumno.Grado = model.Grado;

                db.SaveChanges();

                return Json(new ResponseMessage { Ok = true, Message = "Alumno editado exitosamente!" });

            }
        }



    }
}

BaseProject/Controllers/EstadisticasController.cs
using BaseProject.DB;
using BaseProject.Models.Resultados;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    
    [Authorize(Roles = "estadisticas_primaria,estadisticas_secundaria")]
    public class EstadisticasController : Controller
    {
        // GET: Estadisticas
        public ActionResult Index(int idModalidad)
        {
            using (var db = new VotacionesEntities())
            {
                var Planillas = db.Planilla.Where(x => x.ModalidadId == idModalidad & x.AdjuntoStream != null).ToList();
                var lstPlanillas = new List<ResultadosPlanilla>();

                Planillas.ForEach(x =>
                {
                    lstPlanillas.Add(new ResultadosPlanilla
                    {
                        Planilla = x.Planilla1,
                        Total = db.Votos.Where(f => f.PlanillaId == x.Id).Count()
                    });
                });

                var resultado = new PlanillaEncViewModel { idModalidad = idModalidad };

                resultado.lstPlanilla = lstPlanillas;


                return View(resultado);
            }
        }

        public ActionResult ObtenerGrafico(int idModalidad)
        {
            using (var db = new VotacionesEntities())
            {
                var Planillas = db.Planilla.Where(x => x.ModalidadId == idModalidad & x.AdjuntoStream != null).ToList();
                var lstPlanillas = new List<ResultadosPlanilla>();

                Planillas.ForEach(x =>
                {
                    lstPlanillas.Add(new ResultadosPlanilla
                    {
                        Planilla = x.Planilla1,
                        Total = db.Votos.Where(f => f.PlanillaId == x.Id).Count()
                    });
                });

                var resultado = new PlanillaEncViewModel
                {
                    idModalidad = idModalidad,
                    CantidadVotosTotales = db.Votos.Where(x => x.Alumnos.ModalidadId == idModalidad).Count()
                };

                resultado.lstPlanilla = lstPlanillas;

                return Json(resultado, JsonRequestBehavior.AllowGet);

            }
        }


    }
}

BaseProject/Controllers/PlanillaController.cs
using BaseProject.DB;
using BaseProject.Models;
using BaseProject.Models.Planilla;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    [Authorize(Roles = "it_mantenimiento")]
    public class PlanillaController : Controller
    {
        // GET: Planilla
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult ObtenerTabla()
        {
            using(var db = new VotacionesEntities())
            {
                var data = db.Planilla.Select(x => new PlanillaViewModel
                {
                    Eslogan = x.Eslogan,
                    Id = x.Id,
                    ModalidadId = x.ModalidadId,
                    Planilla = x.Planilla1
                }).ToList();

                return Json(new { data = data }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult CrearPlanilla()
        {
            using(var db = new VotacionesEntities())
            {
                var lstAlumnos = db.Alumnos.Where(x => x.ModalidadId == 1).AsEnumerable().Select(x => new SelectListItem
                {
                    Text = $"{x.Identidad} - {x.Nombre}",
                    Value = x.Id.ToString()
                }).ToList();

                return View(new PlanillaViewModel { 
                    lstAlumnos = lstAlumnos
                });
            }
        }

        [HttpPost]
        public ActionResult CrearPlanilla(PlanillaViewModel model)
        {
            using(var db = new VotacionesEntities())
            {
                var planilla = new Planilla
                {
                    Eslogan = model.Eslogan,
                    ModalidadId = model.ModalidadId,
                    Planilla1 = model.Planilla
                };

                db.Planilla.Add(planilla);
                db.SaveChanges();

                model.lstDetalle.ForEach(x =>
                {
                    var detalle = new Planilla_Detalle
                    {
                        PlanillaId = planilla.Id,
                        AlumnoId = x.AlumnoId,
                        CargoId = x.CargoId,
                        AdjuntoStram = System.Convert.FromBase64String(x.base64)
                    };

                    db.Planilla_Detalle.Add(detalle);
                    db.SaveChanges();
                });


                return Json(new { id = planilla.Id }, JsonRequestBehavior.AllowGet);

            }
        }

        [HttpGet]
        public ActionResult AlumnosPorModalidad(int idModalidad)
        {
            using(var db = new VotacionesEntities())
            {
                var lstAlumnos = db.Alumnos.Where(x => x.ModalidadId == idModalidad).AsEnumerable().Select(x => new SelectListItem
                {
                    Text = $"{x.Identidad} - {x.Nombre}",
                    Value = x.Id.ToString()
                }).ToList();

                return Json(lstAlumnos, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult SubirAdjuntoPlanilla(int idPlanilla)
        {
            using (var db = new VotacionesEntities())
            {

                foreach (string fileName in Request.Files)
                {
                    var file = Request.Files[fileName];
                    if (file == null) continue;
                    var tipoContenido = file.ContentType;
                    var adjunto = new BinaryReader(file.InputStream).ReadBytes(Convert.ToInt32(file.InputStream.Length));

                    var planilla = db.Planilla.FirstOrDefault(x => x.Id == idPlanilla);

                    planilla.AdjuntoStream = adjunto;

                    db.SaveChanges();
                }
                   
                return null;
            }
        }

        public ActionResult EditarPlanilla(int idPlanilla)
        {
            using(var db = new VotacionesEntities())
            {

                var planillaEnc = db.Planilla.Where(x => x.Id == idPlanilla).Select(x => new PlanillaViewModel { 
                    Id = x.Id,
                    Eslogan = x.Eslogan,
                    ModalidadId = x.ModalidadId,
                    Planilla = x.Planilla1
                }).FirstOrDefault();


                var lstAlumnos = db.Alumnos.Where(x => x.ModalidadId == planillaEnc.ModalidadId).AsEnumerable().Select(x => new SelectListItem
                {
                    Text = $"{x.Identidad} - {x.Nombre}",
                    Value = x.Id.ToString()
                }).ToList();

                planillaEnc.lstAlumnos = lstAlumnos;

                return View(planillaEnc);

            }
        }

        [HttpPost]
        public ActionResult EditarPlanilla(PlanillaViewModel model)
        {
            try
            {
                using (var db = new VotacionesEntities())
                {
                    var planilla = db.Planilla.FirstOrDefault(x => x.Id == model.Id);
                    planilla.Planilla1 = model.Planilla;
                    planilla.ModalidadId = model.ModalidadId;
                    planilla.Eslogan = model.Eslogan;

                    db.SaveChanges();

                    return Json(new ResponseMessage { Ok = true, Message = $"{model.Id}" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch(Exception ex) { return Json(new ResponseMessage { Ok = false, Message = $"error" }, JsonRequestBehavior.AllowGet); }
        }

        public ActionResult ObtenerAdjunto(int idPlanilla)
        {
            using(var db = new VotacionesEntities())
            {
                var adjunto = db.Planilla.Where(x => x.Id == idPlanilla).AsEnumerable().Select(x => new PlanillaAdjuntoViewModel
                {
                    Id = x.Id,
                    AdjuntoStream = x.AdjuntoStream,
                    Tipo = "image/jpeg",
                    Nombre = $"{x.Planilla1}{x.Id}",
                    AdjuntoLength = Convert.ToBase64String(x.AdjuntoStream).Length.ToString()
                }).FirstOrDefault();

                return Json(adjunto, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult DescargarAdjunto(int idPlanilla)
        {
            using(var db = new VotacionesEntities())
            {
                var adjunto = db.Planilla.FirstOrDefault(x => x.Id == idPlanilla);

                return File(adjunto.AdjuntoStream, "image/jpeg", $"{adjunto.Planilla1}{adjunto.Id}");
            }
        }

        public JsonResult GetDetallePlanilla(int idPlanilla)
        {
            using(var db = new VotacionesEntities())
            {
                var detalles = db.Planilla_Detalle.Where(x => x.PlanillaId == idPlanilla).Select(x => new DetallePlanilla
                {
                    Id = x.Id,
                    Alumno = x.Alumnos.Nombre,
                    Cargo = x.Cargos.Descripcion,
                    AlumnoId = x.AlumnoId
                }).ToList();

                return Json(new { data = detalles }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult ObtenerImagen(int Id)
        {
            using (var db = new VotacionesEntities())
            {
                var detalles = db.Planilla_Detalle.FirstOrDefault(x => x.Id == Id);

                return File(detalles.AdjuntoStram, "image/jpeg");
            }
        }

        [HttpPost]
        public JsonResult AgregarCargoEstudiante(DetallePlanilla detalle)
        {
            try
            {
                using(var db = new VotacionesEntities())
                {
                    var planilla = new Planilla_Detalle
                    {
                        AlumnoId = detalle.AlumnoId,
                        CargoId = detalle.CargoId,
                        AdjuntoStram = System.Convert.FromBase64String(detalle.base64),
                        PlanillaId = detalle.idPlanilla
                    };

                    db.Planilla_Detalle.Add(planilla);
                    db.SaveChanges();

                    return Json(new ResponseMessage { Ok = true, Message = "guardado" }, JsonRequestBehavior.AllowGet);

                }
            }catch(Exception ex) { return Json(new ResponseMessage { Ok = false, Message = "Error" }, JsonRequestBehavior.AllowGet); }
        }


        [HttpPost]
        public JsonResult EliminarCargoEstudiante(int idEstudiante, int idPlanilla)
        {
            try
            {
                using (var db = new VotacionesEntities())
                {
                    var data = db.Planilla_Detalle.FirstOrDefault(x => x.AlumnoId == idEstudiante & x.PlanillaId == idPlanilla);
                    db.Planilla_Detalle.Remove(data);
                    db.SaveChanges();
                    return Json(new ResponseMessage { Ok = true, Message = $"Borrado" }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex) { return Json(new ResponseMessage { Ok = true, Message = $"error" }, JsonRequestBehavior.AllowGet); }
        }

    }
}

BaseProject/Controllers/ResultadosController.cs
using BaseProject.DB;
using BaseProject.Models.Resultados;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    [Authorize(Roles = "resultados_primaria,resultados_secundaria")]
    public class ResultadosController : Controller
    {
        // GET: Resultados
        public ActionResult Index(int idModalidad)
        {
            using(var db = new VotacionesEntities())
            {
                var Planillas = db.Planilla.Where(x => x.ModalidadId == idModalidad & x.AdjuntoStream != null).ToList();
                var lstPlanillas = new List<ResultadosPlanilla>();

                Planillas.ForEach(x =>
                {
                    lstPlanillas.Add(new ResultadosPlanilla
                    {
                        Planilla = x.Planilla1,
                        Total = db.Votos.Where(f => f.PlanillaId == x.Id).Count()
                    });
                });

                var resultado = new PlanillaEncViewModel { idModalidad = idModalidad };

                resultado.lstPlanilla = lstPlanillas;


                return View(resultado);
            }
            
        }

        public ActionResult GetTabla(int idModalidad)
        {
            using(var db = new VotacionesEntities())
            {
                var data = db.Votos.Where(x => x.Alumnos.ModalidadId == idModalidad).Select(x => new InformeResultadosViewModel { 
                    Estudiante = x.Alumnos.Nombre,
                    Planilla = x.Planilla.Planilla1,
                    Grado = x.Alumnos.Grado,
                    Jornada = x.Alumnos.Jornada,
                    Seccion = x.Alumnos.Seccion
                }).ToList();

                return Json(new { data = data }, JsonRequestBehavior.AllowGet);
            }
        }

        


    }
}

BaseProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-us">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>VOTACIONES</title>

    @*<link rel="shortcut icon" href="~/img/bp-ico.icoo" type="image/x-icon" />*@
    <link runat="server" rel="shortcut icon" href="~/Favicon/favicon.ico" type="image/x-icon" />
    <link runat="server" rel="icon" href="~/Favicon/favicon.ico" type="image/ico" />
    <!--STYLESHEET-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;subset=latin" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    

    <link href="~/Template/css/themes/type-c/theme-dark.min.css" rel="stylesheet" />
    
</head>

<body>
    @Html.Partial("_PartialModal")
    <div id="container" class="effect aside-float aside-bright mainnav-lg" style="background-image: url('../../Template/premium/boxed-bg/polygon/bg/3.jpg'); background-repeat: no-repeat; background-size: cover; background-attachment: fixed;">

        <!--NAVBAR-->
        <!--===================================================-->
        @if (User.Identity.IsAuthenticated)
        {
            @Html.Partial("_PartialHeader")
        }

        <!--===================================================-->
        <!--END NAVBAR-->

        <div class="boxed">

            <!--CONTENT CONTAINER-->
            <!--===================================================-->
            <div id="content-container">
                <div id="page-head">

                    <!--Page Title-->
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    @*<div id="page-title">
                    <h1 class="page-header text-center"><b>BP WALLET</b></h1>
                    </div>*@
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    <!--End page title-->
                    <!--Breadcrumb-->
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    @*<ol class="breadcrumb">
                        <li><a href="#"><i class="pli-home"></i></a></li>
                        <li><a href="#">Library</a></li>
                        <li class="active">Data</li>
                    </ol>*@
                    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                    <!--End breadcrumb-->


                </div>

                <!--Page content-->
                <!--===================================================-->
                <div id="page-content">
                    @RenderBody()
                </div>


                <!--Floating Button-->
                <!--===================================================-->
                @*@if (User.IsInRole("Registros_Acceso"))
                {
                    <a class="btn btn-success float in" href="javascript:void(0)" onclick="MostrarCrearRegistro()" style="position: fixed; animation: jellyIn 0.8s ease 0s 1 normal none running;">
                        <i class="fa fa-pencil-alt my-float"></i>
                    </a>

                    <div class="label-container">
                        <div class="label-text">Nuevo Registro</div>
                        <i class="fa fa-play label-arrow"></i>
                    </div>

                }*@

                <!--===================================================-->
                <!--End page content-->
            </div>
            <!--===================================================-->
            <!--END CONTENT CONTAINER-->
            <!--MAIN NAVIGATION-->

            @if (User.Identity.IsAuthenticated)
            {
                @Html.Partial("_PartialMenu")
                <!--===================================================-->
                <!--END MAIN NAVIGATION-->
                <!--ASIDE-->
                <!--===================================================-->
                @Html.Partial("_PartialAside")
            }
            <!--===================================================-->
            <!--===================================================-->
            <!--END ASIDE-->

        </div>



        <!-- FOOTER -->
        <!--===================================================-->
        @*@Html.Partial("_PartialFooter")*@
        <!--===================================================-->
        <!-- END FOOTER -->
        <!-- SCROLL PAGE BUTTON -->
        <!--===================================================-->
        <button class="scroll-top btn">
            <i class="pci-chevron chevron-up"></i>
        </button>






        <!--===================================================-->
    </div>
    <!--===================================================-->
    <!-- END OF CONTAINER -->
    <!--JAVASCRIPT-->
    <!--=================================================-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/plugins")
    @Scripts.Render("~/bundles/personalized")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)

</body>
</html>

<style>

    .error {
        color: #a94442;
        /*margin-left: 12px;*/
    }
    .status2 {
        position: relative;
        background-repeat: no-repeat;
        background-position: center;
    }

</style>

BaseProject/Views/Shared/_PartialFooter.cshtml
<footer id="footer">

    <!-- Visible when footer positions are fixed -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <div class="show-fixed pad-rgt pull-right">
        You have <a href="#" class="text-main"><span class="badge badge-danger">3</span> pending action.</a>
    </div>



    <!-- Visible when footer positions are static -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <div class="hide-fixed pull-right pad-rgt">
        14GB of <strong>512GB</strong> Free.
    </div>



    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
    <!-- Remove the class "show-fixed" and "hide-fixed" to make the content always appears. -->
    <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

    <p class="pad-lft">&#0169; 2018 Your Company</p>



</footer>

BaseProject/Views/Shared/_PartialMenu.cshtml
<nav id="mainnav-container">
    <div id="mainnav">
        <!--OPTIONAL : ADD YOUR LOGO TO THE NAVIGATION-->
        <!--It will only appear on small screen devices.-->
        <link href="~/Template/css/Layout.css" rel="stylesheet" />
        <div class="mainnav-brand">
            <a href="index.html" class="brand">
                <img src="~/img/voto.png" width="50%"  alt="Logo" class="brand-icon" />
            
                <span class="brand-text">VOTACIONES</span>
            </a>
            <a href="#" class="mainnav-toggle"><i class="ion-close-round icon-lg"></i></a>
        </div>

        <!--Menu-->
        <!--================================-->
        <div id="mainnav-menu-wrap">
            <div class="nano">
                <div class="nano-content">

                    <!--Profile Widget-->
                    <!--================================-->
                    <div id="mainnav-profile" class="mainnav-profile">
                        <div class="profile-wrap text-center">
                            <div class="pad-btm">
                                <img class="img-circle img-md" src="~/Template/img/profile-photos/1.png" alt="Profile Picture">
                            </div>
                            <a href="#profile-nav" class="box-block" data-toggle="collapse" aria-expanded="false">
                                <span class="pull-right dropdown-toggle">
                                    <i class="dropdown-caret"></i>
                                </span>
                                <p class="mnp-name">@User.Identity.Name</p>
                                <span class="mnp-desc">Usuario</span>
                            </a>
                        </div>
                        <div id="profile-nav" class="collapse list-group bg-trans">
                            <a href="#" class="list-group-item">
                                <i class="fas fa-key"></i> Cambiar Contraseña
                            </a>
                            <a href="@Url.Action("LogOff", "Account")" class="list-group-item">
                                <i class="pli-unlock icon-lg icon-fw"></i> Cerrar Sesion
                            </a>
                        </div>
                    </div>


                    @if (User.IsInRole("seguridad"))
                    {
                        <ul id="mainnav-menu" class="list-group">

                            <li class="list-header">Seguridad</li>
                            <li>
                                <a href="@Url.Action("Usuario","Seguridad")">
                                    <i class="fa fa-user fa-fw"></i>
                                    <span class="menu-title"><strong>Usuarios</strong></span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Roles","Seguridad")">
                                    <i class="fas fa-user-lock fas-fw"></i>
                                    <span class="menu-title"><strong>Permisos</strong></span>
                                </a>
                            </li>

                            <li class="list-divider"></li>
                        </ul>
                    }

                    @if (User.IsInRole("resultados_primaria") || User.IsInRole("resultados_secundaria"))
                    {
                        <ul id="mainnav-menu" class="list-group">
                            <li class="list-header">Resultados</li>
                            <li>

                                @if (User.IsInRole("resultados_primaria"))
                                {
                                    <a href="@Url.Action("Index","Resultados")?idModalidad=1">
                                        <i class="fas fa-file-word fas-fw"></i>
                                        <span class="menu-title"><strong>Resultados Primaria</strong></span>
                                    </a>
                                }

                                @if (User.IsInRole("resultado_secundaria"))
                                {
                                    <a href="@Url.Action("Index","Resultados")?idModalidad=2">
                                        <i class="fas fa-file-word fas-fw"></i>
                                        <span class="menu-title"><strong>Resultados Secundaria</strong></span>
                                    </a>
                                }
                            </li>
                            <li class="list-divider"></li>

                        </ul>
                    }

                    @if (User.IsInRole("estadisticas_primaria") || User.IsInRole("estadisticas_secundaria"))
                    {
                        <ul id="mainnav-menu" class="list-group">
                            <li class="list-header">Estadisticas</li>

                            <li>

                                @if (User.IsInRole("estadisticas_primaria"))
                                {
                                    <a href="@Url.Action("Index","Estadisticas")?idModalidad=1">
                                        <i class="fas fa-poll-h fas-fw"></i>
                                        <span class="menu-title"><strong>Estadisticas Primaria</strong></span>
                                    </a>
                                }

                                @if (User.IsInRole("estadisticas_secundaria"))
                                {
                                    <a href="@Url.Action("Index","Estadisticas")?idModalidad=2">
                                        <i class="fas fa-poll-h fas-fw"></i>
                                        <span class="menu-title"><strong>Estadisticas Secundaria</strong></span>
                                    </a>
                                }
                            </li>
                            <li class="list-divider"></li>
                        </ul>
                    }

                    @if (User.IsInRole("it_mantenimiento"))
                    {
                        <ul id="mainnav-menu" class="list-group">

                            <li class="list-header">Configuraciones</li>
                            <li>
                                <a href="@Url.Action("Index","Alumnos")">
                                    <i class="fas fa-users fa-fw"></i>
                                    <span class="menu-title"><strong>Estudiantes</strong></span>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index","Planilla")">
                                    <i class="fas fa-address-card fa-fw"></i>
                                    <span class="menu-title"><strong>Planillas</strong></span>
                                </a>
                            </li>


                            <li class="list-divider"></li>
                        </ul>
                    }






                </div>
            </div>
        </div>

    </div>
</nav>