BaseProject/Models/Roles/CrearRolViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaseProject.Models.Roles
{
    public class CrearRolViewModel
    {
        public int Pk_IdRol { get; set; }
        public string Nombre { get; set; }
        public string Observacion { get; set; }
        public bool Activo { get; set; }

        public bool EsEditar { get; set; }
    }
}

BaseProject/Models/Roles/ListaPermisosPorRolViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaseProject.Models.Roles
{
    public class ListaPermisosPorRolViewModel
    {
        public string Id { get; set; }
        public string Nombre { get; set; }
        public bool Seleccionado { get; set; }
    }
}

BaseProject/Models/Seguridad/PermisosPorUsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaseProject.Models.Seguridad
{
    public class PermisosPorUsuarioViewModel
    {
        public Guid UserId { get; set; }
        public Guid RoleId { get; set; }
        public string Usuario { get; set; }
        public string Nombre { get; set; }
        public string DescripcionRol { get; set; }
        public string Rol { get; set; }
        public int Asignado { get; set; }
    }
}

BaseProject/Models/Seguridad/RolViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaseProject.Models.Seguridad
{
    public class RolViewModel
    {
        public Guid idAplicaccion { get; set; }
        public Guid RoleId { get; set; }
        public string RoleName { get; set; }
        public string descripcion { get; set; }
    }
}

BaseProject/Models/Seguridad/SucursalViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaseProject.Models
{
    public class SucursalViewModel
    {
        public int id { get; set; }
        public string sucursal { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
    }
}

BaseProject/Models/Seguridad/UsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Models.Seguridad
{
    public class UsuarioViewModel
    {
        public Guid UserId { get; set; }
        public string usuario { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string cargo { get; set; }
        public string contrasena { get; set; }
    }
}

BaseProject/Models/Usuario/CambiarContraseñaUsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BaseProject.Models.Usuario
{
    public class CambiarContraseñaUsuarioViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Nueva Contrasena")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar Contrasena")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

BaseProject/Models/Usuario/CrearUsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BaseProject.Models.Usuario
{
    public class CrearUsuarioViewModel
    {
        public int Id { get; set; }
        public string IdAspnetUser { get; set; }

        [Required]
        public string Nombre { get; set; }

        [Required]
        public string Apellido { get; set; }

        [Required]
        [Display(Name = "Fecha de Nacimiento")]
        public System.DateTime FechaNacimiento { get; set; }

        public string Telefono { get; set; }

        public System.DateTime FechaCreado { get; set; }

        public bool Activo { get; set; }

        public Nullable<int> Fk_IdAvatarUsuario { get; set; }

        //aspnetuser
        [Required]
        [Display(Name = "Correro Electronico")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Nombre de Usuario")]
        public string UserName { get; set; }

        [Required]
        [Display(Name = "Rol de Usuario")]
        public int IdRol { get; set; }

        [Display(Name = "Rol")]
        public string NombreRol { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "El {0} tiene que ser al menos de {2} caracteres.", MinimumLength = 4)]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar Contraseña")]
        [Compare("Password", ErrorMessage = "la contraseña y la confirmacion no son el mismo")]
        public string ConfirmPassword { get; set; }


    }
}

BaseProject/Models/Usuario/ListaDeUsuariosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaseProject.Models.Usuario
{
    public class ListaDeUsuariosViewModel : CrearUsuarioViewModel
    {
        public bool EsUsuarioKid { get; set; }
        public string UrlAvatar { get; set; }

    }
}

BaseProject/Controllers/SeguridadController.cs
using BaseProject.Models;
using BaseProject.Models.Seguridad;
using BaseProject.Repositories.SeguridadManager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    [Authorize(Roles = "seguridad")]
    public class SeguridadController : Controller
    {
        private readonly ISeguridadManager _seguridad;

        public SeguridadController(ISeguridadManager seguridad)
        {
            _seguridad = seguridad;
        }

        #region Usuario

        // GET: Seguridad
        public ActionResult Usuario()
        {
            return View();
        }

        public JsonResult GetTablaUsuario()
        {
            return Json(new { data = _seguridad.ObtenerUsuarios() }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CrearUsuario()
        {
            return PartialView(new UsuarioViewModel());
        }

        [HttpPost]
        public ActionResult CrearUsuario(UsuarioViewModel model)
        {
            var response = _seguridad.CrearUsuario(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditarUsuario(string usuario)
        {
            var data = _seguridad.ObtenerUsuario(usuario);
            return PartialView(data);
        }

        [HttpPost]
        public ActionResult EditarUsuario(UsuarioViewModel model)
        {
            var response = _seguridad.EditarUsuario(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ChangePassword(string usuario)
        {
            var model = _seguridad.ObtenerUsuario(usuario);
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult ChangePassword(UsuarioViewModel model)
        {
            var response = _seguridad.CambiarContrasena(model);

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Roles

        public ActionResult Roles()
        {
            return View();
        }

        public JsonResult GetTablaRoles()
        {
            var data = _seguridad.ObtenerListaRoles();
            return Json(new { data = data}, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CrearRol()
        {
            var model = _seguridad.ModelCrearRol();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult CrearRol(RolViewModel model)
        {
            var response = _seguridad.CrearRol(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditarRol(string RoleName)
        {
            var model = _seguridad.ObtenerRolPorNombre(RoleName);
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult EditarRol(RolViewModel model)
        {
            var response = _seguridad.EditarRol(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Sucursales

        public ActionResult Sucursales()
        {
            return View();
        }

        public JsonResult GetTablaSucursales()
        {
            return Json(new { data = _seguridad.ObtenerSucursales() }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CrearSucursal()
        {
            return PartialView(new SucursalViewModel { });
        }

        [HttpPost]
        public ActionResult CrearSucursal(SucursalViewModel model)
        {
            var response = _seguridad.CrearSucursal(model);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult EditarSucursal(int idSucursal)
        {
            var sucursal = _seguridad.ObtenerSucursalPorId(idSucursal);
            return PartialView(sucursal);
        }

        [HttpPost]
        public ActionResult EditarSucursal(SucursalViewModel model)
        {
            var response = _seguridad.EditarSucursal(model);

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region PermisosPorUsuario

        public ActionResult AsignarPermisos(string usuario)
        {
            var datosUsuario = _seguridad.ObtenerUsuario(usuario);

            var model = new PermisosPorUsuarioViewModel
            {
                Nombre = datosUsuario.nombre,
                UserId = datosUsuario.UserId,
                Usuario = usuario
            };

            return PartialView(model);
        }

        public ActionResult ObtenerPermisos(Guid userId)
        {
            var data = _seguridad.ObtenerRoles(userId);

            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GuardarSeleccionPermisos(Guid UserId, List<PermisosPorUsuarioViewModel> ListaDetalle)
        {
            var response = _seguridad.AsignarRoles(UserId, ListaDetalle);
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #endregion

    }
}

BaseProject/Views/Seguridad/AsignarPermisos.cshtml
@model BaseProject.Models.Seguridad.PermisosPorUsuarioViewModel

<div class="panel">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fas fa-plus-circle fa-fw"></i> Asignar Permisos al usuario: @Model.Nombre</h1>
    </div>
    <div class="panel-body">
        <form id="frmRol" method="post">
            <div class="form-horizontal">

                <table class="table table-responsive table-bordered" style="width:100%;" id="dtRoles">
                    <thead>
                        <tr>
                            <th style="width:100%;">Permisos</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>

                <div class="widget-footer">
                    <button type='button' class='btn btn-danger' data-dismiss='modal'><i class="text-lg ion-close-round"></i> Cerrar</button>
                    <button type="button" class="btn btn-success js-asignarRoles"><i class="text-lg ion-checkmark-round"></i> Guardar</button>
                </div>

            </div>

        </form>

    </div>
</div>

<script>

    var dtRoles;

    $(document).ready(function () {

        dtRoles = $('#dtRoles').DataTable({
            autoWidth: true,
            responsive: true,
            language: {
                "emptyTable": "No se encontraron resultados.",
                "search": '<div class="icon-addon addon-md"><label for="search" class="ion-search"></label>',
                "paginate": {
                    first: "Primero",
                    previous: "Anterior",
                    next: "Siguiente",
                    last: "Ultimo"
                },
                "lengthMenu": " _MENU_ ",
                "info": "Mostrando registros del _START_ al _END_ de _TOTAL_ registros totales.",
                "infoEmpty": "No hay registros para mostrar.",
            },
            "ajax": {
                url: '@Url.Action("ObtenerPermisos", "Seguridad")',
                global: false,
                data: { userId: '@Model.UserId' },
                "type": "GET",
                "datatype": "json",
                "error": function (xhr, status, error) { }
            },
            columns: [
                {
                    data: null,
                    render: function (data, type, row) {

                        return '<div class="checkbox"> <input id="check-'+row.RoleId+'" class="magic-checkbox" type="checkbox" ' + (row.Asignado == 1 ? 'checked' : '') + ' name="checkboxItem" /><label for="check-'+row.RoleId+'">' + row.Rol +'</label> </div>';
                    }
                }
            ]
        });

    });

    $("#dtRoles tbody").on('click', 'input[type="checkbox"]', function (e) {
        var $row = $(this).closest('tr');
        var data = dtRoles.row($row).data();
        data.Asignado = this.checked ? 1 : 2;
        e.stopPropagation();
    });


    $(document).on('click', '.js-asignarRoles', function () {
        var ListaDetalle = [];
        var dt = $.fn.dataTable.Api('#dtRoles');

        dt.rows().every(function (rowIdx, tableLoop, rowLoop) {
            ListaDetalle.push(this.data());
        });

        $.ajax({
            url: "@Url.Action("GuardarSeleccionPermisos", "Seguridad")",
            type: 'POST',
            data: { UserId: '@Model.UserId', ListaDetalle: ListaDetalle },
            success: function (data) {
                if (data.Ok) {
                    $("#myModal").modal("hide");
                    AlertaAjax(data);
                } else {
                    AlertaAjax(data);
                }
            }
            
        });


    });

</script>

BaseProject/Views/Seguridad/ChangePassword.cshtml
@model BaseProject.Models.Seguridad.UsuarioViewModel

<div class="panel">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fas fa-key fa-fw"></i> Cambiar Contraseña a @Model.nombre</h1>
    </div>
    <div class="panel-body">
        <form id="frmPassword" method="post">
            <div class="form-horizontal">

                @Html.HiddenFor(model => model.UserId)
                @Html.HiddenFor(model => model.usuario)

                <div class="form-group">
                    <label class="col-lg-12">Nueva contraseña: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.contrasena, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>
                



                <div class="widget-footer">
                    <button type='button' class='btn btn-danger' data-dismiss='modal'><i class="text-lg ion-close-round"></i> Cerrar</button>
                    <button type="submit" class="btn btn-success"><i class="text-lg ion-checkmark-round"></i> Guardar</button>
                </div>

            </div>

        </form>

    </div>
</div>

<script>

    $(document).ready(function () {

        $('#frmPassword').validate({
            ignore: [],
            rules: {
                contrasena: {
                    required: true,
                    minlength: 5
                }
            },
            messages: {
                contrasena: {
                    required: "Contraseña requerida",
                    minlength: "Por Favor introduzca al menos 5 caracteres para la contraseña"
                }
            },
            submitHandler: function (form) {

                $.ajax({
                    url: "@Url.Action("ChangePassword","Seguridad")",
                    type: "post",
                    dataType: "JSON",
                    data: $(form).serialize(),
                    beforeSend: function () {
                        LoadWaitNotification();
                    },
                    complete: function () {
                        UnloadWaitNotification();
                    },
                    success: function (data) {
                        if (data.Ok) {
                            //exito("Advertencia","Usuario creado exitosamente!");
                            $("#myModal").modal("hide");
                            dtUsuarios.ajax.reload(null, false);
                        }
                        else {
                            //fallo("Advertencia", data.Msj);
                        }
                    }
                });

                return false;
            }
        });

    });

</script>

BaseProject/Views/Seguridad/CrearRol.cshtml
@model BaseProject.Models.Seguridad.RolViewModel

<div class="panel">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fas fa-plus-square fa-fw"></i> Nuevo Permiso</h1>
    </div>
    <div class="panel-body">
        <form id="frmRol" method="post">
            <div class="form-horizontal">

                @Html.HiddenFor(model => model.idAplicaccion)

                <div class="form-group">
                    <label class="col-lg-12">Rol: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.RoleName, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-12">Descripcion: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>

                <div class="widget-footer">
                    <button type='button' class='btn btn-danger' data-dismiss='modal'><i class="text-lg ion-close-round"></i> Cerrar</button>
                    <button type="submit" class="btn btn-success"><i class="text-lg ion-checkmark-round"></i> Guardar</button>
                </div>

            </div>

        </form>

    </div>
</div>

<script>

    $(document).ready(function (){

        $('#frmRol').validate({
            ignore: [],
            rules: {
                RoleName: {
                    required: true
                },
                descripcion: {
                    required: true
                }

            },
            messages: {
                RoleName: {
                    required: "Rol requerido"
                },
                descripcion: {
                    required: "Descripcion requerida"
                }
            },
            submitHandler: function (form) {

                $.ajax({
                    url: "@Url.Action("CrearRol","Seguridad")",
                    type: "post",
                    dataType: "JSON",
                    data: $(form).serialize(),
                    /*beforeSend: function () {
                        LoadWaitNotification();
                    },
                    complete: function () {
                        UnloadWaitNotification();
                    },*/
                    success: function (data) {
                        if (data.Ok) {
                            $("#myModal").modal("hide");
                            dtRoles.ajax.reload(null, false);
                            AlertaAjax(data);
                        }
                        else {
                            AlertaAjax(data);
                        }
                    }
                });

                return false;
            }
        });

    });

</script>

BaseProject/Views/Seguridad/CrearSucursal.cshtml
@model BaseProject.Models.SucursalViewModel

<div class="panel">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fa fa-building fa-fw"></i> Crear Sucursal</h1>
    </div>
    <div class="panel-body">
        <form id="frmSucursal" method="post">
            <div class="form-horizontal">

                <div class="form-group">
                    <label class="col-lg-12">Sucursal: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.sucursal, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-12">Direccion: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-12">Telefono: </label>
                    <div class="col-lg-12">
                        <input class="form-control input-lg numeric" id="telefono" name="telefono" type="text" />
                        
                    </div>
                </div>

                <div class="widget-footer">
                    <button type='button' class='btn btn-danger' data-dismiss='modal'><i class="text-lg ion-close-round"></i> Cerrar</button>
                    <button type="submit" class="btn btn-success"><i class="text-lg ion-checkmark-round"></i> Guardar</button>
                </div>

            </div>
            
        </form>

    </div>
</div>


<script>

    $(document).ready(function () {

        $(".numeric").keypress(function (e) {
            if (String.fromCharCode(e.keyCode).match(/[^0-9]/g)) return false;
        });

        $('#frmSucursal').validate({
            ignore: [],
            rules: {
                sucursal: {
                    required: true
                },
                direccion: {
                    required: true
                },
                telefono: {
                    required: true,
                    maxlength: 10,
                    minlength:8
                }
            },
            messages: {
                sucursal: {
                    required: "Nombre de la Sucursal requerido"
                },
                direccion: {
                    required: "Direccion de la Sucursal requerida"
                },
                telefono: {
                    required: "Telefono de la Sucursal requerido",
                    maxlength: "Ingrese un Maximo de 10 números",
                    minlength: "Ingrese un minimo de 9 números"
                }
            },
            submitHandler: function (form) {

                $.ajax({
                    url: "@Url.Action("CrearSucursal", "Seguridad")",
                    type: "post",
                    dataType: "JSON",
                    data: $(form).serialize(),
                    beforeSend: function() {
                        LoadWaitNotification();
                    },
                    complete: function() {
                        UnloadWaitNotification();
                    },
                    success: function (data) {
                        if (data.Ok) {
                            
                            $("#myModal").modal("hide");
                            dtSucursales.ajax.reload(null, false);
                            AlertaAjax(data);
                        }
                        else {
                            AlertaAjax(data);
                        }
                    }
                });

                return false;
            }
        });
    });


</script>

BaseProject/Views/Seguridad/CrearUsuario.cshtml
@model BaseProject.Models.Seguridad.UsuarioViewModel

<div class="panel">
    <div class="panel-heading">
        <h1 class="panel-title"><i class="fas fa-plus-square fa-fw"></i> Crear Ususario</h1>
    </div>
    <div class="panel-body">
        <form id="frmUsuario" method="post">
            <div class="form-horizontal">

                <div class="form-group">
                    <label class="col-lg-12">Nombre: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-lg-12">Usuario: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.usuario, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-12">Correo: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-12">Cargo: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.cargo, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-12">Contraseña: </label>
                    <div class="col-lg-12">
                        @Html.EditorFor(model => model.contrasena, new { htmlAttributes = new { @class = "form-control" } })

                    </div>
                </div>



                <div class="widget-footer">
                    <button type='button' class='btn btn-danger' data-dismiss='modal'><i class="text-lg ion-close-round"></i> Cerrar</button>
                    <button type="submit" class="btn btn-success"><i class="text-lg ion-checkmark-round"></i> Guardar</button>
                </div>

            </div>

        </form>

    </div>
</div>


<script>

    $(document).ready(function (){

        $('#frmUsuario').validate({
            ignore: [],
            rules: {
                nombre: {
                    required: true
                },
                usuario: {
                    required: true
                },
                contrasena: {
                    required: true,
                    minlength: 5
                },
                email: {
                    email: true
                },
                cargo: {
                    required: true
                }

            },
            messages: {
                nombre: {
                    required: "Nombre del usuario requerido"
                },
                usuario: {
                    required: "Usuario requerido"
                },
                contrasena: {
                    required: "Contraseña requerida",
                    minlength: "Por Favor introduzca al menos 5 caracteres para la contraseña"
                },
                email: {
                    email: "Ingrese una direccion de correo valida"
                },
                cargo: {
                    required: "Ingrese cargo del usuario"
                }
            },
            submitHandler: function (form) {

                $.ajax({
                    url: "@Url.Action("CrearUsuario","Seguridad")",
                    type: "post",
                    dataType: "JSON",
                    data: $(form).serialize(),
                    beforeSend: function () {
                        LoadWaitNotification();
                    },
                    complete: function () {
                        UnloadWaitNotification();
                    },
                    success: function (data) {
                        if (data.Ok) {
                            $("#myModal").modal("hide");
                            dtUsuarios.ajax.reload(null, false);
                            AlertaAjax(data);
                        }
                        else {
                            AlertaAjax(data);
                        }
                    }
                });

                return false;
            }
        });

    });

</script>