BaseProject/Models/Votacion/VotacionPlanilla.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaseProject.Models.Votacion
{
    public class VotacionPlanilla
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Identidad { get; set; }
        public string Jornada { get; set; }
        public string Grado { get; set; }
        public string Seccion { get; set; }
        public int ModalidadId { get; set; }
        public string Modalidad
        {
            get { return ObtenerListadoModalidad(ModalidadId); }
            set { }
        }

        public string ObtenerListadoModalidad(int idModalidad)
        {
            return (idModalidad == 1) ? "Primaria" : "Secundaria";
        }

        public List<PlanillaEnc> lstPlanilla { get; set; }


    }


    public class PlanillaEnc
    {
        public int Id { get; set; }
        public string PlanillaNombre { get; set; }
        public string Logo { get; set; }
        public List<PlanillaDet> lstDetalle { get; set; }

    }

    public class PlanillaDet
    {
        public string Alumno { get; set; }
        public string Cargo { get;set; }
        public int CargoId { get; set; }
        public string base64Img { get; set; }

    }


}

BaseProject/Models/Votacion/VotacionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaseProject.Models.Votacion
{
    public class VotacionViewModel
    {
        public string Identidad { get; set; }
    }
}

BaseProject/Controllers/VotacionController.cs
using BaseProject.DB;
using BaseProject.Models;
using BaseProject.Models.Votacion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseProject.Controllers
{
    public class VotacionController : Controller
    {
        // GET: Votacion
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ValidarEstudiante(VotacionViewModel model)
        {
            using(var db = new VotacionesEntities())
            {
                var existe = db.Alumnos.FirstOrDefault(x => x.Identidad == model.Identidad);

                if (existe == null)
                    return Json(new ResponseMessage { Ok = false, Message = $"Error no se encontro ningun alumno con el numero de identitdad {model.Identidad}" });

                var Yavoto = db.Votos.FirstOrDefault(x => x.AlumnoId == existe.Id);

                if (Yavoto != null)
                    return Json(new ResponseMessage { Ok = false, Message = $"El estudiante {existe.Nombre} ya voto!" });


                var hayPlanilla = db.Planilla.FirstOrDefault(x => x.ModalidadId == existe.ModalidadId);

                if(hayPlanilla == null)
                    return Json(new ResponseMessage { Ok = false, Message = $"Error no se encontro ninguna planilla para la modalidad del alumno" });

                return Json(new ResponseMessage { Ok = true, Message = $"" });
            }
        }

        [HttpGet]
        public ActionResult VotacionPlanilla(string identidad)
        {
            using(var db = new VotacionesEntities())
            {
                var existe = db.Alumnos.FirstOrDefault(x => x.Identidad == identidad);

                if (existe == null)
                    return RedirectToAction("index");

                var Yavoto = db.Votos.FirstOrDefault(x => x.AlumnoId == existe.Id);

                if(Yavoto != null)
                    return RedirectToAction("index");


                var estudiante = db.Alumnos.Where(x => x.Identidad == identidad).Select(x => new VotacionPlanilla
                {
                    Id = x.Id,
                    Grado = x.Grado,
                    Identidad = x.Identidad,
                    Jornada = x.Jornada,
                    ModalidadId = x.ModalidadId,
                    Nombre = x.Nombre,
                    Seccion = x.Seccion
                }).FirstOrDefault();

                var listaPlanilla = db.Planilla.Where(x => x.ModalidadId == estudiante.ModalidadId & x.AdjuntoStream != null).Select(x => new PlanillaEnc
                {
                    Id = x.Id,
                    Logo = x.Eslogan,
                    PlanillaNombre = x.Planilla1

                }).ToList();

                listaPlanilla.ForEach(x => x.lstDetalle = db.Planilla_Detalle.Where(f => f.PlanillaId == x.Id).Select(f => new PlanillaDet
                        {
                            Alumno = f.Alumnos.Nombre,
                            CargoId = f.CargoId,
                            Cargo = f.Cargos.Descripcion
                        }).ToList()
                    );

                estudiante.lstPlanilla = listaPlanilla;
                
                return View(estudiante);

            }
            
        }

        public ActionResult ObtenerEsloganPlanilla(int idPlanilla)
        {
            using(var db = new VotacionesEntities())
            {
                var model = db.Planilla.FirstOrDefault(x => x.Id == idPlanilla);

                return File(model.AdjuntoStream, "image/jpeg");
            }
        }

        public ActionResult ObtenerImagenesCandidatos(int idPlanilla, int idCandidato)
        {
            using(var db = new VotacionesEntities())
            {
                var detalle = db.Planilla_Detalle.FirstOrDefault(x => x.PlanillaId == idPlanilla & x.CargoId == idCandidato);

                return File(detalle.AdjuntoStram, "image/jpeg");
            }
        }

        [HttpPost]
        public ActionResult GuardarVotacion(int IdAlumno, int IdPlanilla)
        {
            using (var db = new VotacionesEntities())
            {
                var voto = new Votos
                {
                    AlumnoId = IdAlumno,
                    PlanillaId = IdPlanilla
                };

                db.Votos.Add(voto);

                db.SaveChanges();

                return Json(new ResponseMessage { Ok = true, Message = "Su voto se ha guardado exitosamente!" });

            }
        }


    }
}

BaseProject/Views/Votacion/Index.cshtml
@model BaseProject.Models.Votacion.VotacionViewModel
@{
    ViewBag.Title = "BPWALLET";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Sistema Votacion Online</title>

    <link runat="server" rel="shortcut icon" href="~/Favicon/favicon.ico" type="image/x-icon" />
    <link runat="server" rel="icon" href="~/Favicon/favicon.ico" type="image/ico" />


    <!--STYLESHEET-->
    <!--=================================================-->
    <!--Open Sans Font [ OPTIONAL ]-->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!--Bootstrap Stylesheet [ REQUIRED ]-->

    <link href="~/Template/css/bootstrap.min.css" rel="stylesheet" />
    <!--Nifty Stylesheet [ REQUIRED ]-->
    <link href="~/Template/css/nifty.min.css" rel="stylesheet">
    <!--Nifty Premium Icon [ DEMONSTRATION ]-->
    <link href="~/Template/css/demo/nifty-demo-icons.min.css" rel="stylesheet">
    <!--=================================================-->
    <!--Pace - Page Load Progress Par [OPTIONAL]-->
    <link href="~/Template/css/pace.min.css" rel="stylesheet">
    <script src="~/Template/js/pace.min.js"></script>
    <link href="~/Template/plugins/bootstrap-sweetalert/sweetalert.css" rel="stylesheet" />
    <!--Demo [ DEMONSTRATION ]-->


    <link href="~/Template/css/themes/type-a/theme-prickly-pear.min.css" rel="stylesheet" />
</head>

<body style="overflow:hidden;background-color:#ffffff" >

    <div id="container" class="effect aside-float" style="background-image: url('../../img/background-votacion.jpeg'); background-repeat: no-repeat; background-size: contain; background-attachment: fixed;">


        <div class="cls-content" style="padding-top:35vh;">
            <div class="cls-content-lg panel">
                <div class="panel-body text-center" style="background-color:transparent;">

                    <form id="frm" method="post">

                        
                        <h3 style="color:#0ab1fc;"><strong>Sistema de Votaciones Estudiantiles</strong></h3>

                        @Html.ValidationSummary(true, "", new { @class = "text-danger text-center" })
                        <div class="form-group">
                            @Html.TextBoxFor(model => model.Identidad, new { @class = "form-control input-lg numeric", @placeholder = "Ingrese su Registro Nacional Estudiantil", @autofocus = true, @maxlength = "13" })
                            @Html.ValidationMessageFor(m => m.Identidad, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <button class="btn btn-info btn-lg btn-block" type="submit">Entrar</button>
                        </div>



                    </form>



                </div>


            </div>
        </div>

    </div>

    <!--jQuery [ REQUIRED ]-->
    <script src="~/Template/js/jquery.min.js"></script>
    <!--BootstrapJS [ RECOMMENDED ]-->
    <script src="~/Template/js/bootstrap.min.js"></script>
    <!--NiftyJS [ RECOMMENDED ]-->
    <script src="~/Template/js/nifty.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Template/js/Personalized/Alertas.js"></script>
    <script src="~/Template/plugins/bootstrap-sweetalert/sweetalert.min.js"></script>
</body>
</html>

<script>

    $(".numeric").keypress(function (e) {
        if (String.fromCharCode(e.keyCode).match(/[^0-9]/)) return false;
    });

    $('#frm').validate({
        ignore: [],
        rules: {
            Identidad: {
                required: true,
                maxlength: 13
            }

        },
        messages: {
            Identidad: {
                required: "Campos requeridos!",
                maxlength: "Ingrese un maximo de 13 caracteres"
            }

        },
        submitHandler: function (form) {

            $.ajax({
                url: "@Url.Action("ValidarEstudiante","Votacion")",
                type: "post",
                dataType: "JSON",
                data: $(form).serialize(),
                //beforeSend: function () {
                //    LoadWaitNotification();
                //},
                //complete: function () {
                //    UnloadWaitNotification();
                //},
                success: function (data) {
                    if (data.Ok) {
                        window.location.href = '@Url.Action("votacionPlanilla","Votacion")?identidad=' + $('#Identidad').val();
                    }
                    else {
                        AlertaAjax(data);
                    }
                }
            });

            return false;

        }
    })




</script>


<style>

    .error{
        color:red;
    }

    .cls-content {
        top: 0.3em;
        right: 15em;
        position: absolute;
    }


</style>
    

    


}

BaseProject/Views/Votacion/VotacionPlanilla.cshtml
@model BaseProject.Models.Votacion.VotacionPlanilla
    <link href="~/Content/slick.css" rel="stylesheet" />
<div class="panel">
    <div class="panel-heading">
        <div class="panel-control">

            <a class="btn btn-warning js-cerrar"><i class="fas fa-sign-out-alt fa-fw"></i>Salir</a>
        </div>
        <h1 class="panel-title">Votacion Estudiantil </h1>
    </div>
    <div class="panel-body">

        <div class="row">

            <div class="col col-lg-12">

                <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Datos del Estudiante</legend>

                    <form id="frm" method="post">
                        <div class="form-horizontal">

                            <div class="row">

                                <div class="col-lg-4 col-md-4">
                                    <div class="form-group">
                                        <label class="col-lg-12">Identidad: <strong>@Model.Identidad</strong></label>

                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <div class="form-group">
                                        <label class="col-lg-12">Nombre: <strong>@Model.Nombre</strong></label>

                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <div class="form-group">
                                        <label class="col-lg-12">Grado: <strong>@Model.Grado</strong></label>

                                    </div>
                                </div>
                                



                            </div>


                            <div class="row">

                                <div class="col-lg-4 col-md-4">
                                    <div class="form-group">
                                        <label class="col-lg-12">Seccion: <strong>@Model.Seccion</strong></label>

                                    </div>
                                </div>

                                <div class="col-lg-4 col-md-4">
                                    <div class="form-group">
                                        <label class="col-lg-12">Jornada: <strong>@Model.Jornada</strong></label>

                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4">
                                    <div class="form-group">
                                        <label class="col-lg-12">Modalidad: <strong>@Model.Modalidad</strong></label>

                                    </div>
                                </div>



                            </div>
                        </div>

                    </form>

                </fieldset>




            </div>

            <div class="col col-lg-12">

                <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Elije la planilla de tu eleccion</legend>

                    <div class="col-lg-12">


                        <div class="slider">

                            @foreach (var lst in Model.lstPlanilla)
                            {
                                <div>
                                    <div class="panel widget">
                                        <div class="widget-header bg-info text-center">
                                            <h2 class="text-light mar-no pad-top">@lst.PlanillaNombre</h2>
                                            <p class="mar-btm">@lst.Logo</p>
                                        </div>
                                        <div class="widget-body bg-dark">
                                            <img alt="Profile Picture" class="widget-img img-circle img-border-light" src="@Url.Action("ObtenerEsloganPlanilla","Votacion")?idPlanilla=@lst.Id">
                                            <div class="pad-all text-center text-mint">
                                                <img alt="Avatar" style="height:120px;width:120px;" class="img-lg img-circle img-border mar-btm" src="@Url.Action("ObtenerImagenesCandidatos","Votacion")?idPlanilla=@lst.Id&idCandidato=@lst.lstDetalle.FirstOrDefault(x => x.CargoId == 1).CargoId">
                                                <h4 class="text-light mar-no">@lst.lstDetalle.FirstOrDefault(x => x.CargoId == 1).Alumno</h4>
                                                <p class="text-light mar-no">@lst.lstDetalle.FirstOrDefault(x => x.CargoId == 1).Cargo</p>
                                                <br />
                                                <ul class="list-unstyled text-center text-light bord-top pad-top mar-no row">


                                                    @foreach (var item in lst.lstDetalle.Where(x => x.CargoId != 1).OrderBy(x => x.CargoId))
                                                    {
                                                        <li class="col-xs-12 col-lg-3">
                                                            <img alt="Avatar" class="img-lg img-circle img-border mar-btm" src="@Url.Action("ObtenerImagenesCandidatos","Votacion")?idPlanilla=@lst.Id&idCandidato=@item.CargoId">

                                                            <p class="text-muted mar-no">@item.Cargo</p>
                                                        </li>
                                                    }

                                                </ul>
                                                <ul class="list-unstyled text-center text-light bord-top pad-top mar-no row">

                                                    <li class="col-xs-12 col-lg-12">
                                                        <button data-planilla="@lst.Id" data-alumno="@Model.Id" class="btn btn-info btn-block btn-lg js-votar">Votar</button>
                                                    </li>

                                                </ul>


                                            </div>

                                        </div>
                                    </div>
                                </div>
                            }


                        </div>
                        <div class="text-center">
                            <button type="button" class="slick-next btn btn-success btn-lg" id="next">Siguiente Planilla</button>

                        </div>

                    </div>







                </fieldset>


            </div>


        </div>



    </div>
</div>




<style>
    #container.mainnav-lg #footer, #container.mainnav-lg #content-container {
        padding-left: 0px !important;
    }

    body, #content-container, #navbar {
        background-color: #ecf0f5;
    }

    .bx-wrapper img {
    }
</style>

@section Scripts{

    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

    <script>

        $(document).ready(function () {
            $('.slider').slick({
                prevArrow: false,
                nextArrow: $('#next')
            });
        });

        $(document).on('click', '.js-votar', function () {
            var planilla = $(this).data('planilla');
            var alumno = $(this).data('alumno');

            $.ajax({
                url: "@Url.Action("GuardarVotacion","Votacion")",
                type: "post",
                dataType: "JSON",
                data: { IdAlumno: alumno,IdPlanilla: planilla },
                beforeSend: function () {
                    LoadWaitNotification();
                },
                complete: function () {
                    UnloadWaitNotification();
                },
                success: function (data) {
                    if (data.Ok) {
                        
                        AlertaAjax(data);

                     var delayInMilliseconds = 3000; //1 second

                    setTimeout(function() {
                        window.location.href = '@Url.Action("index")';
                    }, delayInMilliseconds);

                    }
                    else {
                        AlertaAjax(data);
                    }
                }
            });



        });

        $(document).on('click', '.js-cerrar', function () {
            window.location.href = '@Url.Action("Index","votacion")';

        });


    </script>

}